# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
<a href="user1.jpg">
title:            Lyrrael
tagline:          'A Portfolio'
description:      'A Portfolio'
url:              http://lyrrael.github.io
baseurl:          /

author:
  name:           'Amanda'
  url:            https://twitter.com/lyrrael

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
